# This is a basic workflow to help you get started with Actions

name: merge-files

# Controls when the action will run. 
on: push
  # Triggers the workflow on push 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Run setup script
        run: ./.github/scripts/setup.sh
        shell: bash
        
