# This is a basic workflow to help you get started with Actions

name: SETUP

# Controls when the action will run. 
on: push
  # Triggers the workflow on push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    # Runs a single command using the runners shell
    steps:
      - name: Run build script
        run: ./.github/workflows/setup.sh
        
