# This is a basic workflow to help you get started with Actions

name: merge-files

# Controls when the action will run. 
on: [push, workflow_dispatch]
  # Triggers the workflow on push 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run setup script
        run: |
          cat ./base-file-head.md > README.md
          cat ./OFFICIAL/twitter.md >> README.md
          cat ./OFFICIAL/links.md >> README.md
          cat ./OFFICIAL/announcements.md >> README.md
          cat ./OFFICIAL/others.md >> README.md
          cat ./CLUBS/head.md >> README.md
          cat ./CLUBS/announcements.md >> README.md
          cat ./CLUBS/others.md >> README.md
          git config --global user.email 80387370+res0x01@users.noreply.github.com
          git config --global user.name res0x01
          git commit -a -m "update README.md"
          git push
          cat ./README.md
